SST: SST::Simulation Class Reference
SST::Simulation Class Reference abstract
Main control class for a SST Simulation.
#include <simulation.h>
Public Types
enum Mode_t { UNKNOWN, INIT, RUN, BOTH }
Type of Run Modes.
Public Member Functions
virtual Mode_t getSimulationMode () const =0
Get the run mode of the simulation (e.g.
virtual SimTime_t getCurrentSimCycle () const =0
Return the current simulation time as a cycle count.
virtual SimTime_t getEndSimCycle () const =0
Return the end simulation time as a cycle count.
virtual int getCurrentPriority () const =0
Return the current priority.
virtual UnitAlgebra getElapsedSimTime () const =0
Return the elapsed simulation time as a time.
virtual UnitAlgebra getFinalSimTime () const =0
Return the end simulation time as a time.
virtual RankInfo getRank () const =0
Get this instance's parallel rank.
virtual RankInfo getNumRanks () const =0
Get the number of parallel ranks in the simulation.
virtual std::string & getOutputDirectory ()=0
Returns the output directory of the simulation.
virtual void requireEvent (const std::string &name)=0
Signifies that an event type is required for this simulation Causes the Factory to verify that the required event type can be found.
virtual void printStatus (bool fullStatus)=0
Causes the current status of the simulation to be printed to stderr.
Static Public Member Functions
static Simulation * getSimulation ()
Return a pointer to the singleton instance of the Simulation.
static SharedRegionManager * getSharedRegionManager ()
Returns the Simulation's SharedRegionManager.
static TimeLord * getTimeLord (void)
Return the TimeLord associated with this Simulation.
static Output & getSimulationOutput ()
Return the base simulation Output class instance.
Protected Member Functions
Simulation (Simulation const &)
void operator= (Simulation const &)
Detailed Description
Main control class for a SST Simulation.
Provides base features for managing the simulation
Member Enumeration Documentation
enum SST::Simulation::Mode_t
Type of Run Modes.
Enumerator
UNKNOWN
Unknown mode - Invalid for running
INIT
Initialize-only. Useful for debugging initialization and graph generation
RUN
Run-only. Useful when restoring from a checkpoint (not currently supported)
BOTH
Default. Both initialize and Run the simulation
Member Function Documentation
virtual std::string& SST::Simulation::getOutputDirectory () pure virtual
Returns the output directory of the simulation.
Returns
Directory in which simulation outputs are placed
Implemented in SST::Simulation_impl.
Simulation * SST::Simulation::getSimulation () static
Return a pointer to the singleton instance of the Simulation.
Simulation functions.
Static functions
Referenced by SST::Link::addRecvLatency(), SST::Event::clone(), SST::Factory::CreateModule(), SST::Exit::execute(), SST::Event::generateUniqueId(), SST::SharedRegionManagerImpl::getGlobalSharedRegion(), SST::SharedRegionManagerImpl::getLocalSharedRegion(), SST::RegionInfo::getMergeInfo(), SST::Statistics::StatisticOutputTxt::implStartOutputEntries(), SST::Statistics::StatisticOutputCSV::implStopOutputEntries(), SST::Link::recv(), SST::Exit::refDec(), SST::Link::replaceFunctor(), SST::Link::send(), SST::Link::setFunctor(), SST::Statistics::StatisticOutputJSON::startOfSimulation(), SST::Statistics::StatisticOutputTxt::startOfSimulation(), and SST::Statistics::StatisticOutputCSV::startOfSimulation().
virtual Mode_t SST::Simulation::getSimulationMode () const pure virtual
Get the run mode of the simulation (e.g.
init, run, both etc)
Implemented in SST::Simulation_impl.
virtual void SST::Simulation::printStatus (bool fullStatus) pure virtual
Causes the current status of the simulation to be printed to stderr.
Parameters
fullStatus - if true, call printStatus() on all components as well as print the base Simulation's status
Implemented in SST::Simulation_impl.
virtual void SST::Simulation::requireEvent (const std::string & name) pure virtual
Signifies that an event type is required for this simulation Causes the Factory to verify that the required event type can be found.
Parameters
name fully qualified libraryName.EventName
Implemented in SST::Simulation_impl.
The documentation for this class was generated from the following files:
src/sst/core/simulation.h
src/sst/core/simulation.cc